[root at 2023-02-28 00:04:07,185]: Archipelago (0.3.9) logging initialized on Linux-6.1.12-x64v3-xanmod1-x86_64-with-glibc2.35 running Python 3.10.6
[root at 2023-02-28 00:04:07,199]: Uncaught exception
Traceback (most recent call last):
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 417, in handle_option
    player_option = option.from_any(get_choice(option_key, game_weights))
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 276, in get_choice
    raise RuntimeError(f"All options specified in \"{option}\" are weighted as zero.")
RuntimeError: All options specified in "progression_balancing" are weighted as zero.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 178, in main
    tuple(roll_settings(yaml, args.plando) for yaml in weights_cache[path])
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 178, in <genexpr>
    tuple(roll_settings(yaml, args.plando) for yaml in weights_cache[path])
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 473, in roll_settings
    handle_option(ret, game_weights, option_key, option, plando_options)
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 420, in handle_option
    raise Exception(f"Error generating option {option_key} in {ret.game}") from e
Exception: Error generating option progression_balancing in Muse Dash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 643, in <module>
    main()
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 197, in main
    raise ValueError(f"File {path} is destroyed. Please fix your yaml.") from e
ValueError: File Glaceon_Muse_Dash - Tristan “shadowmrt241” Evenson.yaml is destroyed. Please fix your yaml.
